added ramdisk mounting support

diff --git a/run.sh.in b/run.sh.in
--- a/run.sh.in
+++ b/run.sh.in
@@ -34,6 +34,18 @@ module load sac/amd-prod-git
 shopt -s nullglob
 set -bm
 
+# activate ramdisk mounting
+MOUNT=true
+
+# because of HDD space limits, we need to mount a ramdrive
+# this has to happen first otherwise things could go fubar.
+if [ "$MOUNT" = true ]; then
+    if ! mount /tmp; then
+        error "unable to mount /tmp"
+        exit 10
+    fi
+fi
+
 # SETUP SCRIPT
 WORKDIR="$(mktemp -d)"
 STAGE="NULL"
@@ -134,6 +146,15 @@ finish()
     test -d /tmp/.nvprof && rm -rf /tmp/.nvprof
     inf "Deleting workdir..."
     rm -rf "${WORKDIR}"
+
+    # if we mounted our ramdrive we need to unmount it now
+    # XXX this should only be safe on GPU nodes
+    if [ "$MOUNT" = true ] && grep -q '/tmp' /etc/mtab; then
+        if ! umount /tmp; then
+            error "unable to umount /tmp"
+            exit 10
+        fi
+    fi
 }
 
 error_handling()
