Support multiple build flags per target

diff --git a/run.sh.template b/run.sh.template
--- a/run.sh.template
+++ b/run.sh.template
@@ -10,6 +10,8 @@
 #SBATCH --exclusive
 #SBATCH --partition amd-longq
 #SBATCH --time 60
+#SBATCH --mail-type=FAIL
+#SBATCH --mail-user=hans@viess.mn
 #SBATCH --gres=gpu:k20:1
 #SBATCH --cpus-per-task 2
 #SBATCH --output /tmp/sac-bench-system.log
@@ -60,7 +62,9 @@ state()
     echo "  dir structure:"
     ls -la ${WORKDIR}
     echo "LOCALDIR = ${PWD}"
-    if [ ! -z "${buildflags}" ]; then echo "BUILDFLAGS = ${buildflags}"; fi
+    [ -z "${target}" ] || echo "TARGET = ${varient}"
+    [ -z "${varient}" ] || echo "VARIENT = ${varient}"
+    [ -z "${buildflags}" ] || echo "BUILDFLAGS = ${buildflags}"
 }
 
 save_logs()
@@ -72,7 +76,8 @@ save_logs()
     if [ ! -z $logs ]; then
         log "saving ${logs[@]}"
         tar -cf "${BENCHSUITE}-${BENCHNAME}-result.tar" "${logs[@]}"
-        mv "${WORKDIR}/${BENCHSUITE}-${BENCHNAME}-result.tar" "$LOCALDIR/"
+        [ -d "${LOCALDIR}/results" ] || mkdir "${LOCALDIR}/results"
+        mv "${WORKDIR}/${BENCHSUITE}-${BENCHNAME}-result.tar" "${LOCALDIR}/results/"
     else
         log "no logs to save"
     fi
@@ -87,15 +92,16 @@ finish()
 
 error_handling()
 {
-    log "An error was detected, exitting..."
+    log "An error was detected, getting state information"
     state
-    exit 1
+    log "Trying to continue..."
 }
 
 handle_child()
 {
     if [[ $? -eq 139 ]]; then
         log "current run has segfaulted, no output could be saved"
+        error_handling
     fi
 }
 
@@ -109,12 +115,14 @@ trap handle_child CHLD
 
 pushd "${WORKDIR}"
 for source in ${SOURCES[@]}; do
+    count=0
     for target in ${TARGETS[@]}; do
         for varient in ${VARIENTS[@]}; do
-            buildflags="$(eval echo "\${BUILDFLAGS_${varient//\'}}")"
+            buildflags="$(eval echo "\${BUILDFLAGS_${varient}[${count}]}")"
             log "compiling target '$target' varient '$varient' with \`${buildflags}'"
             $SAC2C ${buildflags} -t $target -o "${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" "${LOCALDIR}/${source}"
         done
+        count+=1
     done
 done
 popd
