Major changes, more generic interface

diff --git a/run.sh.template b/run.sh.template
--- a/run.sh.template
+++ b/run.sh.template
@@ -28,95 +28,93 @@ module load sac/amd-dev-git
 shopt -s nullglob
 set -bm
 
-# SETUP SAC
-SAC2C="$(which sac2c_d)"
+# SETUP SCRIPT
 WORKDIR="$(mktemp -d)"
 STAGE="NULL"
 declare -A SKIP
 LOGFILE="output.log"
 LOCALDIR="@PWD@"
+# shellcheck disable=SC2034
+VERBOSITY=4 # info
 
 # PROFILE
 @PROFILE@
 
-# HELPER FUNCTIONS
+# STDLIB
+# shellcheck disable=SC1091
+source @PWD@/modules/logging.bash
+# shellcheck disable=SC1091
+source @PWD@/modules/sysinfo.bash
+# shellcheck disable=SC1091
+source @PWD@/modules/misc.bash
 
-log()
-{
-    printf "[%s](${BENCHSUITE}-${BENCHNAME}): %s\n" "$(date +'%F %T %Z')" "$1" >> "${WORKDIR}/${LOGFILE}"
-}
-
-log_column()
-{
-    printf "          %-20s = %-20s\n" "$1" "$2" >> "${WORKDIR}/${LOGFILE}"
-}
+# REDIRECTS
+exec 2>&1 >&3 # redirect stdout and stderr to fd 3 (logger)
 
 log_dir()
 {
     local -a content=( "${1}"/* )
-    printf "              ..........................................................\n" "$(date +'%F %T %Z')" >> "${WORKDIR}/${LOGFILE}"
-    for i in ${content[@]}; do
+    printf "              ..........................................................\n" >> "${WORKDIR}/${LOGFILE}"
+    for i in "${content[@]}"; do
         printf "              %s\n" "$(basename $i)" >> "${WORKDIR}/${LOGFILE}"
     done
-    printf "              ..........................................................\n" "$(date +'%F %T %Z')" >> "${WORKDIR}/${LOGFILE}"
+    printf "              ..........................................................\n" >> "${WORKDIR}/${LOGFILE}"
 }
 
 state()
 {
-    printf " #################################################################################\n" >> "${WORKDIR}/${LOGFILE}"
-    log_column "STAGE" "${STAGE}"
-    log_column "SAC2C" "${SAC2C}"
-    log_column "WORKDIR" "${WORKDIR}"
+    arraylog "STAGE = ${STAGE}" "COMPILER = ${COMPILER}" \
+        "WORKDIR = ${WORKDIR}" "LOCALDIR = ${LOCALDIR}"  \
+        "TARGET = ${target:-unset}"                      \
+        "VARIENT = ${varient:-unset}"                    \
+        "BUILDFLAGS = ${buildflags:-unset}"
     log_dir "${WORKDIR}"
-    log_column "LOCALDIR" "${LOCALDIR}"
-    [ -z "${target}" ] || log_column "TARGET" "${target}"
-    [ -z "${varient}" ] || log_column "VARIENT" "${varient}"
-    [ -z "${buildflags}" ] || log_column "BUILDFLAGS" "${buildflags}"
-    printf " #################################################################################\n" >> "${WORKDIR}/${LOGFILE}"
 }
 
 save_logs()
 {
-    log "saving workdir logs..."
+    inf "saving workdir logs..."
 
-    pushd "$WORKDIR"
+    pushd "$WORKDIR" || exit 10
     logs=( *.log )
-    if [ ! -z $logs ]; then
-        log "saving ${logs[@]}"
-        tar -cf "${BENCHSUITE}-${BENCHNAME}-result.tar" "${logs[@]}"
-        [ $? -ne 0 ] && error_handling
+    if [ "${#logs[@]}" -gt 0 ]; then
+        inf "saving ${logs[*]}"
+        if ! tar -cf "${BENCHSUITE}-${BENCHNAME}-result.tar" "${logs[@]}"; then
+            error_handling
+        fi
         [ -d "${LOCALDIR}/results/${BENCHSUITE}-${BENCHNAME}" ] || mkdir -p "${LOCALDIR}/results/${BENCHSUITE}-${BENCHNAME}"
-        mv "${WORKDIR}/${BENCHSUITE}-${BENCHNAME}-result.tar" "${LOCALDIR}/results/${BENCHSUITE}-${BENCHNAME}/"
-        [ $? -ne 0 ] && error_handling
+        if ! mv "${WORKDIR}/${BENCHSUITE}-${BENCHNAME}-result.tar" "${LOCALDIR}/results/${BENCHSUITE}-${BENCHNAME}/"; then
+            error_handling
+        fi
     else
-        log "no logs to save"
+        inf "no logs to save"
     fi
-    popd
+    popd || exit 10
 }
 
 finish()
 {
-    log "Removing NVPROF tmp dir, if it exists"
+    inf "Removing NVPROF tmp dir, if it exists"
     test -d /tmp/.nvprof && rm -rf /tmp/.nvprof
-    log "Deleting workdir..."
+    inf "Deleting workdir..."
     rm -rf "${WORKDIR}"
 }
 
 error_handling()
 {
-    log "An error was detected, getting state information"
+    error "An error was detected, getting state information"
     state
     if [ "x${STAGE}" = "xBUILD" ]; then
-        log " will skip running \`${target}-${varient}' later..."
+        warn "will skip running \`${target}-${varient}' later..."
         SKIP["${target}-${varient}"]=1
     fi
-    log "Trying to continue..."
+    inf "Trying to continue..."
 }
 
 handle_child()
 {
     if [[ $? -eq 139 ]]; then
-        log "current run has segfaulted, no output could be saved"
+        error "current run has segfaulted, no output could be saved"
         error_handling
     fi
 }
@@ -128,55 +126,36 @@ trap finish EXIT
 trap handle_child CHLD
 
 # we move to the workdir
-pushd "${WORKDIR}"
+pushd "${WORKDIR}" || exit 10
 
 # GET SYSTEM INFO
 
 STAGE='INFO'
-
-# Printout as much information as is good :-)
-cat > "${LOGFILE}" <<HERE
-## System information:
-  Date: $(date)
-    OS: $(lsb_release -s -d)
- Linux: $(uname -a)
-   SAC: $(sac2c_d -V)
-   GCC: $(gcc -dumpversion)
-  NVCC: $(nvcc --version | tail -n1)
-
-   CPU:
-    model - $(grep -m 1 "model name" /proc/cpuinfo |cut -d' ' -f 4-)
-      mhz - $(grep -m 1 "cpu MHz" /proc/cpuinfo |cut -d' ' -f 3-)
-
-   GPU:
-$(nvidia-smi --query-gpu=name,driver_version --format=csv,noheader)
-
-   Mem:
-     free - $(grep MemFree /proc/meminfo | cut -d' ' -f 2-)
-    total - $(grep MemTotal /proc/meminfo | cut -d' ' -f 2-)   
-##
-HERE
+sysinfo
 
 # COMPILE BENCHMARK
 
 STAGE="BUILD"
 
 if [ "x${MODE}" = "xMANUAL" ]; then
-    for source in ${SOURCES[@]}; do
+    for source in "${SOURCES[@]}"; do
         cp -r "${LOCALDIR}/${source}" "${WORKDIR}/"
     done
 
     # call build function
-    build &>> "${LOGFILE}"
+    capture build
 else
-    for source in ${SOURCES[@]}; do
+    for source in "${SOURCES[@]}"; do
         count=0
-        for target in ${TARGETS[@]}; do
-            for varient in ${VARIENTS[@]}; do
+        for target in "${TARGETS[@]}"; do
+            for varient in "${VARIENTS[@]}"; do
                 buildflags="$(eval echo "\${BUILDFLAGS_${varient}[${count}]}")"
-                log "compiling target '$target' varient '$varient' with \`${buildflags}'"
-                $SAC2C ${buildflags} -t $target -o "${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" "${LOCALDIR}/${source}" &> "sac2c-build-${target}-${varient}.log"
-                [ $? -ne 0 ] && error_handling
+                binary_name="${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out"
+                build_log="${WORKDIR}/sac2c-build-${target}-${varient}.log"
+                inf "compiling target '$target' varient '$varient' with \`${buildflags}'"
+                if ! $COMPILER "${buildflags}" -t "$target" -o "${binary_name}" "${LOCALDIR}/${source}" &> "${build_log}"; then
+                    error_handling
+                fi
             done
             count+=1
         done
@@ -189,7 +168,7 @@ STAGE="INPUT"
 
 if [ ${#INPUTS[@]} -ne 0 ]; then
     for input in "${INPUTS[@]}"; do
-        log "copying $input to workdir ${WORKDIR}"
+        inf "copying $input to workdir ${WORKDIR}"
         cp -r "${LOCALDIR}/${input}" "${WORKDIR}/"
     done
 fi
@@ -201,45 +180,54 @@ STAGE="RUN"
 
 if [ "x${MODE}" = "xMANUAL" ]; then
     # call run function
-    run &>> "${LOGFILE}"
+    capture run
 else
-    for target in ${TARGETS[@]}; do
-        for varient in ${VARIENTS[@]}; do
+    for target in "${TARGETS[@]}"; do
+        for varient in "${VARIENTS[@]}"; do
             if [ ${SKIP[${target}-${varient}]-0} -gt 0 ]; then
+                inf "SKIPPING target '$target' and varient '$varient'"
                 continue
             fi
-            if [ ! -e "${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" ]; then
-                log "binary missing!"
+            binary_name="${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out"
+            binary_log="${WORKDIR}/${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.log"
+            if [ ! -e "${binary_name}" ]; then
+                error "Binary missing! SKIPPING target '$target' and varient '$varient'"
                 state
-                log "trying to continue..."
                 continue
             fi
-            log "RUNNING target '$target' and varient '$varient'"
+            inf "RUNNING target '$target' and varient '$varient'"
             if [ -z "${STDINS}" ]; then
-                /usr/bin/time -p -o "timerfile" -f "${TFORMAT}" ./"${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" "${RUNFLAGS}" > "${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.log" 2>> "${LOGFILE}"
+                if ! /usr/bin/time -p -o "timerfile" -f "${TFORMAT}" ./"${binary_name}" "${RUNFLAGS}" > "${binary_log}" 2>> "${LOGFILE}"; then
+                    error_handling
+                fi
             else
-                /usr/bin/time -p -o "timerfile" -f "${TFORMAT}" ./"${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" "${RUNFLAGS}" < "${STDINS}" > "${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.log" 2>> "${LOGFILE}"
+                if ! /usr/bin/time -p -o "timerfile" -f "${TFORMAT}" ./"${binary_name}" "${RUNFLAGS}" < "${STDINS}" > "${binary_log}" 2>> "${LOGFILE}"; then
+                    error_handling
+                fi
             fi
-            [ $? -ne 0 ] && error_handling # FIXME we need something more sane here
-            cat "timerfile" >> "${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.log"
+            cat "timerfile" >> "${binary_log}"
 
             if [[ "${target}" =~ "cuda" ]]; then
-                log "Doing CUDA run"
+                inf "Doing CUDA run"
+                cuda_log="${WORKDIR}/nvprof-${target}-${varient}.csv.log"
                 if [ -z "${STDINS}" ]; then
-                    nvprof --profile-api-trace all --unified-memory-profiling per-process-device -u ms --csv --log-file "nvprof-${target}-${varient}.csv.log" ./"${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" "${RUNFLAGS}" > /dev/null 2>> "${LOGFILE}"
+                    if ! nvprof --profile-api-trace all --unified-memory-profiling per-process-device -u ms --csv --log-file "${cuda_log}" ./"${binary_name}" "${RUNFLAGS}" > /dev/null 2>> "${LOGFILE}"; then
+                        error_handling
+                    fi
                 else
-                    nvprof --profile-api-trace all --unified-memory-profiling per-process-device -u ms --csv --log-file "nvprof-${target}-${varient}.csv.log" ./"${BENCHSUITE}-${BENCHNAME}-${target}-${varient}.out" "${RUNFLAGS}" < "${STDINS}" > /dev/null 2>> "${LOGFILE}"
+                    if ! nvprof --profile-api-trace all --unified-memory-profiling per-process-device -u ms --csv --log-file "${cuda_log}" ./"${binary_log}" "${RUNFLAGS}" < "${STDINS}" > /dev/null 2>> "${LOGFILE}"; then
+                        error_handling
+                    fi
                 fi
-                [ $? -ne 0 ] && error_handling # FIXME we need something more sane here
             fi
         done
     done
 fi
 
 # we leave the workdir
-popd
+popd || exit 10
 
-log "done running"
+inf "done running"
 
 # SAVE LOGS
 
